name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MEICASH_POSTGRES_PORT: 5432
      MEICASH_POSTGRES_DB: juazeiro_meicash
      MEICASH_POSTGRES_USER: time_cinco
      MEICASH_POSTGRES_PASSWORD: pass_time_cinco
      MEICASH_TEST_POSTGRES_PORT: 5435
      MEICASH_TEST_POSTGRES_DB: mandacaru_broker_test
      MEICASH_TEST_POSTGRES_USER: time_cinco_test
      MEICASH_TEST_POSTGRES_PASSWORD: mandacaru

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Export environment variables
        run: export $(grep -v '^#' .env | xargs)

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Start Docker
        run: docker-compose up -d db-test

      - name: Build with Maven
        run: mvn --batch-mode clean install

      - name: Stop Docker
        run: docker-compose down